services:
  - type: web
    name: visual-continuity-on-the-web-my-journey-with-view-transitions-demo
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
